---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-secrets
  namespace: mynamespace
spec:
  encryptedData:
    DATABASE_URL: AgBcxKXYK46e0csw0fOsVxwBmkGOKa9o0ZpptztmPcd5vOfIzsTcFjNHzyDY9jIfR2qCoEMQyc4CLUv4dcgxmL7Ph4SZ7kcGlL6P8bDwXtWT0+66vKQqnZjvJYdM+vCnm7ypEyLV2tCH6MjRZBbWNDjR2oc0Hrtx9hJeRhKWI4sUrnEPBwRSLyzxZEMTUimDhb68vOlOD6/4AUEcqE0yrVmRMM7WRxnN+d64kQisC4XuxyNqc+7hpvG8fSHWHfIZDsjzdLT4zSNFeBB57GukrjzKFlz5xhrfE2d3ln9f96ha/by7sCv9+mTldy0ZUXi5JqR2lyOqsoogenq5j+hi/XQYugoYf85+MOB9WcKCPRA4yR5fCiXI2L3ifXRi4EO2m5j0Z4muUy7gXUCXb05CuQxMSYwuStOeRQd0V8rC3rqZE4/LOlJmaSmGOeVDdmNCsCG0MOisZ7e3BgF4PAWa8JojfWQJosAUZFsNAVi46yT/UZbfS5nyHnag6SVsNmzBwgX2U5/GmT23mGv4gJIDdAWgmHCBrNZyVEZ26ANf+nY7TopsrYzI3I0cSwh5ErxtebNaQ/Zk8UxbeTm5tvQoecIcorHkn3g/51BCCRw/3JwQJ8GL9vNLXkJ8ZZ6xs2pq0YN7R38ubgHMsH+RpwEhsBvJwxYjsVfMKrgXAOC1OqJPgfbG7yAmfvZmNPJkohcQGPu5t0E+4gUUKaPxalzyLYx2BDHM8uoE7CueBGS1mRceu7UinuIlMHLqORZjOfilTqqO45oHT4ubxy4y5sIjVcG934HcM97yb9W6OaIoGQUfkcJBI1kxizSDV1/zsddqFB1HluXDgvkv+FUiBkOwlJX1ucQ8VPIZY9Un1JnYwWBjCbKIrlQ4RGsgWr5OB5mFPDK97A==
  template:
    metadata:
      creationTimestamp: null
      name: database-secrets
      namespace: mynamespace
