
notifactions:
  appName: notifactions
 
  image_name: mahmoudkhera/devops2-notifications
  image_tag: latest
  serviceName: notifications
  containerPort: 3002
  service:
    type: ClusterIP
    port: 3002             
    targetPort: 3002       
    #nodePort: 30082   
  configmap:
    name: notifications
    data:
      PORT: '3002'
      HOST: 0.0.0.0
      SMTP_PORT: '587'
      SMTP_FROM: mahmoudkhera20@gmail.com
  secret:
    name: smtp-secrets
    SMTP_HOST: AgCCWCgA2sBGCf7qoOe+78YEqxhCtk26K8hkkGGKEaFa9mMAPxkVURzoTrNHWWLIUuXYeVpy5ZdsCm5JDJ2/BAsiDdhZRzHPYv0OzQmqMDWqSVxNV+zCLRMMdPprgQicPuittaI++wA422YLPY6A7l1leVL+oe5kZsYD7RzVi3ADhBQFBoOV3rqvsACKJ/JoIJGPeOO5sr/OUKlcPt/TKN9XYv8v19Sxa7gUY8oJDWGdsLvv1TnUOIhWPX3FCDLOTNk1kLzW9z+wCKcJQJvs2MyTIxGRMCDASVR1l5r3eF6pSQBMMHSALTj0ieJf2sTSK4zKBtdFf7XaKOz5GRQhvHRwg6SQq6xb5ZWEDGPAFG80guhuvXWRtj3g11T1sDuMOZQhafUYY6Ud43ZTIGTrh/4o+bUORnYE5TTBsPnWdwI3PQfdn3Bjad4mA2rCCDkKKIcZw5o9C24I2KvWpmzwF8UmQcVm4YZAINucgh8M4yTGHYb1aDgCRw3QwWDrFX7C8o6/vpJNLObQrr97H38f4ZWEx+QKZbNd/K019ubaOr+K5C6S23o3geTJEm+0EkzUhSjaz1oz8NYgz2piBCWWel7gBKh2G8PQIJJjLCHIkQ1PZPheUguFcpUrULrFQi+mPCIJQupu1XLYfeFp8RrMg5NsUZ2Ztav/YIUAXCALiBbNbb+wQQLRZI2Kw/pxU07Zu2ycPxUtPaMBGfQNCdrIRF1xvLj7oA==
    SMTP_USER: AgAyVACePfgjNgNWs1IfUuK+32c2rWGMRTWt7PsC4yzG6Xh9tVPJtljc8w0ZpSKvcyHQ9SFhG8dXVKCknLP6SUty8a/KWvtXxOORSXArhHe67S+2t2gchuGY4oHQ7LNtV2sSm12bGTLFkGz/0X5NiQNU52Z4pDSp7Lk0NKtQrnThC5w9ZKYiNmCvk+mVXeK3gQjdZXzmJkAWGwGvJs7bnAbJQGVia7wNny3kAI0IuD/bJgtvCed7MbUUNI89Fscy8Y3NsSGnkQEX4I6pvdQnDKfsyOxKIPin3xqJVssfrna4SiIGFlJOYqZhpd3Dw52Fo5CGy9qmqqJPhVw+j7E6LgLu4IOqVHd6U0DMETgWHlJ2j3BFvnsdJzvohupYX4BJkLxu5fQsHrprqB8Q40+zM6qFs85Q3VJgBngenAOnaG+dMepuzUtWvTZ0jcp5lsfFEdMq5kIRkx5XYHCvDQbIstC3cwwAJLMckjDg/p0ueieOfXZHIo6jt2lyFfcweFRJ1ylzYZMWcof9OyY/YsOOrosoEgyk5XHQTuUcGc0v6X7LNgWhB/fxtOzL+YI4CJ3HGU8fH57Uyo/UZZqUllX5Selrf68/IK9/9EIpD7FwvXZp6Ln66biomUdq2ph6S1yO63Xnobs8MdRZuRYozZWB8t1GTrnz+dhRvJsTMZZSvSKNq4LznncjcdUx9JrqSG2DPPipy5yjbpLsNWkBxHCDBSzQ1bY/urRsgHM=
    SMTP_PASSWORD: AgCMcw0NDvca7MRxZliQ6yp8JObfHcbwdJ5mUbJggxzdvYK27iLvmqexP4EgD3/UnzPNxdPLNDZNKmDApQRPdOo+mV3kd/cb2PCWGoh4araVExwJl9J3pJYSBVHsCyOkXKCeoVaMMniD3f//K0ix0W6OYMx338knPmBNCG8s0kvdTAnL2A1QfV7RAk0V7DfxCmKCKW1c/407c5wjZPAbeTG7+/luB1OO2Gx+xegs7egsv8XO9om0hwwwegeMn9/9/7r0a2BlidIrfcK8moBuqcbyRlQURbtyjPkTWF4Pv9XwWdAm7Yl7iW/sLZ/IHoouadJmwkJdSWz1eT3yfN5Fc1s05BYiCCIt96/mOz4JybfyWvPOykwaToE5nOd7PzF7gMEmQagZrqBwcNlRuNjyBnJkOUIxAAwf+B90IqWUNP4BP+8j0JL59BAKPdqfLvZZrhlcGBRhXuIuXK9lJ0DYAGbZSmDYQxIb4+vJ7U4a3giCQ9pas6Ebmo3RZJKFMIBTfV5NHRStoh1CuUfYhJ9+zCp2caTKT9CLfhoH5ywPVu91Dcz2n0HXM3W+3KPUh0GspGi/KZIOZl0ts8yD98b5Fi62AUz2pafZOWHGrItKg0LAOy3TIZXxzYNNZ9D0u4Exnp//ZgVjGHG5OlULkNkx1eLxFldtt5xXzI8g4u3XW6sMVBtPK9V7yFsyE+KjqxcDPg4Zzf2La6Y5fNPIC949j+ZIcRely98ixHh3G6QzCoVVAqw6Se2G8fV2nWdjZ+oO6+e+inSZjmx81se2QYtxVEM1gGJ57XonGENoQGAflImOwBWp8LPJ+/TwVN8=
