apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.appName}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.frontend.appName}}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.appName}}
        tier: frontend
    spec: 
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image_name }}:{{ .Values.frontend.image_tag }}"
        ports:
        - containerPort: {{.Values.frontend.containerPort}}
        envFrom:
        - configMapRef:
            name: {{ .Values.frontend.configmap.name }}
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    
          limits:
            memory: "128Mi"  
            cpu: "100m"