apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:

        - path: /backend(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ .Values.inventory.serviceName }}
              port:
                name: {{ .Values.inventory.service.port_name }}

        - path: /()(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ .Values.frontend.serviceName }}
              port:
                name: {{ .Values.frontend.service.port_name }}