apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.inventory.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.inventory.appName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.inventory.appName }}
      tier: inventory
  template:
    metadata:
      labels:
        app: {{ .Values.inventory.appName  }}
        tier: inventory
    spec: 
      containers:
      - name: inventory
        image: "{{ .Values.inventory.image_name }}:{{ .Values.inventory.image_tag }}"
        ports:
        - containerPort: {{.Values.inventory.containerPort}}
        envFrom:
        - configMapRef:
            name: {{ .Values.inventory.configmap.name }}
        - secretRef:
            name: {{.Values.inventory.secret.name }}
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    
          limits:
            memory: "128Mi"  
            cpu: "100m"