apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.inventory.secret.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"   # ← only if you sealed with --scope cluster-wide
spec:
  encryptedData:
    DATABASE_URL: {{ .Values.inventory.secret.DATABASE_URL }}
  template:
    metadata:
      name: {{ .Values.inventory.secret.name }}      # ← MUST match metadata.name above
      namespace: {{ .Values.namespace }}              # ← MUST match metadata.namespace above
      labels:
        app: {{ .Values.inventory.appName }}
      annotations:
        managed-by: helm
    type: Opaque