apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.inventory.serviceName }}
  namespace: {{ .Values.namespace  }}
  labels:
    app: {{ .Values.inventory.appName}}
    tier: inventory
spec:
  type: {{ .Values.inventory.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.inventory.service.port | default 80 }}
      targetPort: {{ .Values.inventory.service.targetPort | default 80 }}
      protocol: TCP
      name: {{.Values.inventory.service.port_name}}
      #nodePort: {{ .Values.inventory.service.nodePort }}  
  selector:
    app: {{ .Values.inventory.appName}}
    tier: inventory