apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.notifactions.secret.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    SMTP_HOST: {{ .Values.notifactions.secret.SMTP_HOST  }}
    SMTP_USER: {{ .Values.notifactions.secret.SMTP_USER }}
    SMTP_PASSWORD: {{ .Values.notifactions.secret.SMTP_PASSWORD  }}
  template:
    metadata:
      name: {{ .Values.notifactions.secret.name }}      # ← MUST match metadata.name above
      namespace: {{ .Values.namespace }}              # ← MUST match metadata.namespace above
      labels:
        app: {{ .Values.notifactions.appName }}
      annotations:
        managed-by: helm
    type: Opaque

