apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.notifactions.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.notifactions.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.notifactions.appName }}
      tier: notifactions
  template:
    metadata:
      labels:
        app: {{ .Values.notifactions.appName  }}
        tier: notifactions
    spec: 
      containers:
      - name: notifications
        image: "{{ .Values.notifactions.image_name }}:{{ .Values.notifactions.image_tag }}"
        ports:
        - containerPort: {{.Values.notifactions.containerPort}}
        envFrom:
        - configMapRef:
            name: {{ .Values.notifactions.configmap.name }}
        - secretRef: 
            name: {{ .Values.notifactions.secret.name }}
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    
          limits:
            memory: "128Mi"  
            cpu: "100m"