on:
  workflow_call:
    inputs:
      dir:
        type: string
        required: true
      tag:
        type: string
        required: true
      run_checks:
        type: boolean
        default: true
    outputs:
      digest:
        value: ${{ jobs.build.outputs.digest }}


jobs:
  sast:
    if: inputs.run_checks
    uses: ./.github/workflows/sast.yaml
    with:
      dir: ${{ inputs.dir }}

  deps:
    if: inputs.run_checks
    uses: ./.github/workflows/depnd.yaml
    with:
      dir: ${{ inputs.dir }}

  test:
    if: inputs.run_checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.dir }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ inputs.dir }}/package-lock.json
      - run: npm ci
      - run: echo " not tests not implemented yet  just the job demo"
    
  build:
    needs: [sast, deps, test]
    # run when checks passed OR were skipped (run_checks=false); stop on failure
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      dir: ${{ inputs.dir }}
      tag: ${{ inputs.tag }}
      push: ${{ github.event_name != 'pull_request' }}
    secrets: inherit